/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2.0.2103172220
    Soft IP Version: 1.0.6
    2021 03 26 11:17:51
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module ahbl2apb0 (clk_i, rst_n_i, ahbl_hsel_i, ahbl_hready_i, ahbl_haddr_i,
    ahbl_hburst_i, ahbl_hsize_i, ahbl_hmastlock_i, ahbl_hprot_i, ahbl_htrans_i,
    ahbl_hwdata_i, ahbl_hwrite_i, ahbl_hreadyout_o, ahbl_hresp_o,
    ahbl_hrdata_o, apb_pready_i, apb_pslverr_i, apb_prdata_i, apb_psel_o,
    apb_paddr_o, apb_pwrite_o, apb_pwdata_o, apb_penable_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  rst_n_i;
    input  ahbl_hsel_i;
    input  ahbl_hready_i;
    input  [31:0]  ahbl_haddr_i;
    input  [2:0]  ahbl_hburst_i;
    input  [2:0]  ahbl_hsize_i;
    input  ahbl_hmastlock_i;
    input  [3:0]  ahbl_hprot_i;
    input  [1:0]  ahbl_htrans_i;
    input  [31:0]  ahbl_hwdata_i;
    input  ahbl_hwrite_i;
    output  ahbl_hreadyout_o;
    output  ahbl_hresp_o;
    output  [31:0]  ahbl_hrdata_o;
    input  apb_pready_i;
    input  apb_pslverr_i;
    input  [31:0]  apb_prdata_i;
    output  apb_psel_o;
    output  [31:0]  apb_paddr_o;
    output  apb_pwrite_o;
    output  [31:0]  apb_pwdata_o;
    output  apb_penable_o;
endmodule