/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2.0.2103172220
    Soft IP Version: 1.0.0
    2021 03 26 11:48:51
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module sysclk_rst_gen1 (dut_clk_i, dut_rst_i, dut_clk_o, dut_rst_o, tb_rst_o,
    tb_clk_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  dut_clk_i;
    input  dut_rst_i;
    output  dut_clk_o;
    output  dut_rst_o;
    output  tb_rst_o;
    output  tb_clk_o;
endmodule