/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2.0.2103172220
    Soft IP Version: 1.0.0
    2021 03 26 11:49:38
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module uart_model1 (clk, rstn, uart_rxd, uart_txd, uart_rx_data_debug,
    uart_rx_valid_debug, uart_rx_break_debug, uart_tx_data_debug,
    uart_tx_en_debug, uart_tx_busy_debug)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk;
    input  rstn;
    input  uart_rxd;
    output  uart_txd;
    output  [7:0]  uart_rx_data_debug;
    output  uart_rx_valid_debug;
    output  uart_rx_break_debug;
    output  [7:0]  uart_tx_data_debug;
    output  uart_tx_en_debug;
    output  uart_tx_busy_debug;
endmodule