    uart_model1 __(.clk( ),
        .rstn( ),
        .uart_rxd( ),
        .uart_txd( ),
        .uart_rx_data_debug( ),
        .uart_rx_valid_debug( ),
        .uart_rx_break_debug( ),
        .uart_tx_data_debug( ),
        .uart_tx_en_debug( ),
        .uart_tx_busy_debug( ));
