/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2.0.2104292220
    Soft IP Version: 1.0.2
    2021 06 10 11:27:30
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module sysmem0 (ahbl_hclk_i, ahbl_hresetn_i, ahbl_s0_hsel_i, ahbl_s0_hready_i,
    ahbl_s0_haddr_i, ahbl_s0_hburst_i, ahbl_s0_hsize_i, ahbl_s0_hmastlock_i,
    ahbl_s0_hprot_i, ahbl_s0_htrans_i, ahbl_s0_hwrite_i, ahbl_s0_hwdata_i,
    ahbl_s0_hreadyout_o, ahbl_s0_hresp_o, ahbl_s0_hrdata_o, ahbl_s1_hsel_i,
    ahbl_s1_hready_i, ahbl_s1_haddr_i, ahbl_s1_hburst_i, ahbl_s1_hsize_i,
    ahbl_s1_hmastlock_i, ahbl_s1_hprot_i, ahbl_s1_htrans_i, ahbl_s1_hwrite_i,
    ahbl_s1_hwdata_i, ahbl_s1_hreadyout_o, ahbl_s1_hresp_o, ahbl_s1_hrdata_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ahbl_hclk_i;
    input  ahbl_hresetn_i;
    input  ahbl_s0_hsel_i;
    input  ahbl_s0_hready_i;
    input  [31:0]  ahbl_s0_haddr_i;
    input  [2:0]  ahbl_s0_hburst_i;
    input  [2:0]  ahbl_s0_hsize_i;
    input  ahbl_s0_hmastlock_i;
    input  [3:0]  ahbl_s0_hprot_i;
    input  [1:0]  ahbl_s0_htrans_i;
    input  ahbl_s0_hwrite_i;
    input  [31:0]  ahbl_s0_hwdata_i;
    output  ahbl_s0_hreadyout_o;
    output  ahbl_s0_hresp_o;
    output  [31:0]  ahbl_s0_hrdata_o;
    input  ahbl_s1_hsel_i;
    input  ahbl_s1_hready_i;
    input  [31:0]  ahbl_s1_haddr_i;
    input  [2:0]  ahbl_s1_hburst_i;
    input  [2:0]  ahbl_s1_hsize_i;
    input  ahbl_s1_hmastlock_i;
    input  [3:0]  ahbl_s1_hprot_i;
    input  [1:0]  ahbl_s1_htrans_i;
    input  ahbl_s1_hwrite_i;
    input  [31:0]  ahbl_s1_hwdata_i;
    output  ahbl_s1_hreadyout_o;
    output  ahbl_s1_hresp_o;
    output  [31:0]  ahbl_s1_hrdata_o;
endmodule